#!/bin/bash

filesize=$(stat -c%s "$1")
threshold=104800
if (( filesize > threshold )); then
    echo "输出过长: $filesize 字节"
    exit 1
else
    if t2img -w 1000 -f 'Monospace 18' < "$1" > "$2"; then 
        echo -n "[CQ:image,file=file://$(pwd)/$2]"
    fi
fi
